<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="demo1"
    errors="1" failures="0" hostname="" id="" package="demo1" skipped="0"
    tests="1" time="0.004000" timestamp="Tue, 20 Sep 2016 17:54:12 GMT">
  
    <testcase name="demo test Google" time="0.004000" assertions="0">
    </testcase>
      <system-err>
          Error while running [Demo1 / demo test Google]:

  ReferenceError: Repo is not defined
    at Object.module.exports.demo test Google (C:\NODEJS\workSpace\NightWatchDemo\NightWatchDemo\tests\demo1.js:9:17)
    at Module.call (C:\Users\gflaucher\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\gflaucher\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\gflaucher\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at Promise.then.Q.nextTick.self.promiseDispatch.done (C:\Users\gflaucher\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\gflaucher\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\gflaucher\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\gflaucher\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\gflaucher\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
      </system-err>
  
  
  </testsuite>
</testsuites>
